server:
  port: 8080
spring:
  application:
    name: instagram
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  security:
    user:
      name: user
      password: 1234
      roles: MEMBER

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: springjjang052
    password: 1234
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create

logging:
  level:
    root: info
    org:
      hibernate:
        sql: debug